// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.2
// source: message/validator_out.proto

package message

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ValidatorOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Device unique ID.
	UniqId string `protobuf:"bytes,1,opt,name=uniq_id,json=uniqId,proto3" json:"uniq_id,omitempty"`
	// Device attribute.
	Attr string `protobuf:"bytes,2,opt,name=attr,proto3" json:"attr,omitempty"`
	// Attribute value.
	//
	// Types that are assignable to ValOneof:
	//	*ValidatorOut_IntVal
	//	*ValidatorOut_Fl64Val
	//	*ValidatorOut_StrVal
	//	*ValidatorOut_BoolVal
	//	*ValidatorOut_BytesVal
	ValOneof isValidatorOut_ValOneof `protobuf_oneof:"val_oneof"`
	// Attribute map value. Will be ignored if another value is present.
	MapVal map[string]string `protobuf:"bytes,17,rep,name=map_val,json=mapVal,proto3" json:"map_val,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Timestamp.
	Ts *timestamp.Timestamp `protobuf:"bytes,7,opt,name=ts,proto3" json:"ts,omitempty"`
	// Device ID (UUID).
	DevId string `protobuf:"bytes,8,opt,name=dev_id,json=devId,proto3" json:"dev_id,omitempty"`
	// Organization ID (UUID).
	OrgId string `protobuf:"bytes,9,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Trace ID (UUID).
	TraceId string `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
}

func (x *ValidatorOut) Reset() {
	*x = ValidatorOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_validator_out_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatorOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorOut) ProtoMessage() {}

func (x *ValidatorOut) ProtoReflect() protoreflect.Message {
	mi := &file_message_validator_out_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorOut.ProtoReflect.Descriptor instead.
func (*ValidatorOut) Descriptor() ([]byte, []int) {
	return file_message_validator_out_proto_rawDescGZIP(), []int{0}
}

func (x *ValidatorOut) GetUniqId() string {
	if x != nil {
		return x.UniqId
	}
	return ""
}

func (x *ValidatorOut) GetAttr() string {
	if x != nil {
		return x.Attr
	}
	return ""
}

func (m *ValidatorOut) GetValOneof() isValidatorOut_ValOneof {
	if m != nil {
		return m.ValOneof
	}
	return nil
}

func (x *ValidatorOut) GetIntVal() int64 {
	if x, ok := x.GetValOneof().(*ValidatorOut_IntVal); ok {
		return x.IntVal
	}
	return 0
}

func (x *ValidatorOut) GetFl64Val() float64 {
	if x, ok := x.GetValOneof().(*ValidatorOut_Fl64Val); ok {
		return x.Fl64Val
	}
	return 0
}

func (x *ValidatorOut) GetStrVal() string {
	if x, ok := x.GetValOneof().(*ValidatorOut_StrVal); ok {
		return x.StrVal
	}
	return ""
}

func (x *ValidatorOut) GetBoolVal() bool {
	if x, ok := x.GetValOneof().(*ValidatorOut_BoolVal); ok {
		return x.BoolVal
	}
	return false
}

func (x *ValidatorOut) GetBytesVal() []byte {
	if x, ok := x.GetValOneof().(*ValidatorOut_BytesVal); ok {
		return x.BytesVal
	}
	return nil
}

func (x *ValidatorOut) GetMapVal() map[string]string {
	if x != nil {
		return x.MapVal
	}
	return nil
}

func (x *ValidatorOut) GetTs() *timestamp.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *ValidatorOut) GetDevId() string {
	if x != nil {
		return x.DevId
	}
	return ""
}

func (x *ValidatorOut) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ValidatorOut) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type isValidatorOut_ValOneof interface {
	isValidatorOut_ValOneof()
}

type ValidatorOut_IntVal struct {
	// Integer value, 64-bit.
	IntVal int64 `protobuf:"zigzag64,3,opt,name=int_val,json=intVal,proto3,oneof"`
}

type ValidatorOut_Fl64Val struct {
	// Float value, 64-bit.
	Fl64Val float64 `protobuf:"fixed64,4,opt,name=fl64_val,json=fl64Val,proto3,oneof"`
}

type ValidatorOut_StrVal struct {
	// String value.
	StrVal string `protobuf:"bytes,5,opt,name=str_val,json=strVal,proto3,oneof"`
}

type ValidatorOut_BoolVal struct {
	// Boolean value.
	BoolVal bool `protobuf:"varint,6,opt,name=bool_val,json=boolVal,proto3,oneof"`
}

type ValidatorOut_BytesVal struct {
	// Bytes value.
	BytesVal []byte `protobuf:"bytes,16,opt,name=bytes_val,json=bytesVal,proto3,oneof"`
}

func (*ValidatorOut_IntVal) isValidatorOut_ValOneof() {}

func (*ValidatorOut_Fl64Val) isValidatorOut_ValOneof() {}

func (*ValidatorOut_StrVal) isValidatorOut_ValOneof() {}

func (*ValidatorOut_BoolVal) isValidatorOut_ValOneof() {}

func (*ValidatorOut_BytesVal) isValidatorOut_ValOneof() {}

var File_message_validator_out_proto protoreflect.FileDescriptor

var file_message_validator_out_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x6f, 0x72, 0x5f, 0x6f, 0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc3, 0x03, 0x0a, 0x0c, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x6f, 0x72, 0x4f, 0x75, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x6e, 0x69, 0x71,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x74, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x61, 0x74, 0x74, 0x72, 0x12, 0x19, 0x0a, 0x07, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x12, 0x48, 0x00, 0x52, 0x06, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c,
	0x12, 0x1b, 0x0a, 0x08, 0x66, 0x6c, 0x36, 0x34, 0x5f, 0x76, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x48, 0x00, 0x52, 0x07, 0x66, 0x6c, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x12, 0x19, 0x0a,
	0x07, 0x73, 0x74, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x06, 0x73, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x12, 0x1b, 0x0a, 0x08, 0x62, 0x6f, 0x6f, 0x6c,
	0x5f, 0x76, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x07, 0x62, 0x6f,
	0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x12, 0x1d, 0x0a, 0x09, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x76,
	0x61, 0x6c, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x08, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x56, 0x61, 0x6c, 0x12, 0x3a, 0x0a, 0x07, 0x6d, 0x61, 0x70, 0x5f, 0x76, 0x61, 0x6c, 0x18,
	0x11, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x4f, 0x75, 0x74, 0x2e, 0x4d, 0x61, 0x70,
	0x56, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x6d, 0x61, 0x70, 0x56, 0x61, 0x6c,
	0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x15, 0x0a, 0x06,
	0x64, 0x65, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x65,
	0x76, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72,
	0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72,
	0x61, 0x63, 0x65, 0x49, 0x64, 0x1a, 0x39, 0x0a, 0x0b, 0x4d, 0x61, 0x70, 0x56, 0x61, 0x6c, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x42, 0x0b, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x2c, 0x5a,
	0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x69, 0x6e,
	0x67, 0x73, 0x70, 0x65, 0x63, 0x74, 0x2f, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x67, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_message_validator_out_proto_rawDescOnce sync.Once
	file_message_validator_out_proto_rawDescData = file_message_validator_out_proto_rawDesc
)

func file_message_validator_out_proto_rawDescGZIP() []byte {
	file_message_validator_out_proto_rawDescOnce.Do(func() {
		file_message_validator_out_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_validator_out_proto_rawDescData)
	})
	return file_message_validator_out_proto_rawDescData
}

var file_message_validator_out_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message_validator_out_proto_goTypes = []interface{}{
	(*ValidatorOut)(nil),        // 0: message.ValidatorOut
	nil,                         // 1: message.ValidatorOut.MapValEntry
	(*timestamp.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_message_validator_out_proto_depIdxs = []int32{
	1, // 0: message.ValidatorOut.map_val:type_name -> message.ValidatorOut.MapValEntry
	2, // 1: message.ValidatorOut.ts:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_validator_out_proto_init() }
func file_message_validator_out_proto_init() {
	if File_message_validator_out_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_validator_out_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatorOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_validator_out_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ValidatorOut_IntVal)(nil),
		(*ValidatorOut_Fl64Val)(nil),
		(*ValidatorOut_StrVal)(nil),
		(*ValidatorOut_BoolVal)(nil),
		(*ValidatorOut_BytesVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_validator_out_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_validator_out_proto_goTypes,
		DependencyIndexes: file_message_validator_out_proto_depIdxs,
		MessageInfos:      file_message_validator_out_proto_msgTypes,
	}.Build()
	File_message_validator_out_proto = out.File
	file_message_validator_out_proto_rawDesc = nil
	file_message_validator_out_proto_goTypes = nil
	file_message_validator_out_proto_depIdxs = nil
}
