// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: message/thingspect_validator_in.proto

package message

import (
	common "github.com/thingspect/proto/go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ValidatorIn represents a data point and associated metadata as used in message queues.
type ValidatorIn struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Point       *common.DataPoint      `protobuf:"bytes,1,opt,name=point"`
	xxx_hidden_OrgId       *string                `protobuf:"bytes,2,opt,name=org_id,json=orgId"`
	xxx_hidden_SkipToken   bool                   `protobuf:"varint,3,opt,name=skip_token,json=skipToken"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ValidatorIn) Reset() {
	*x = ValidatorIn{}
	mi := &file_message_thingspect_validator_in_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorIn) ProtoMessage() {}

func (x *ValidatorIn) ProtoReflect() protoreflect.Message {
	mi := &file_message_thingspect_validator_in_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ValidatorIn) GetPoint() *common.DataPoint {
	if x != nil {
		return x.xxx_hidden_Point
	}
	return nil
}

func (x *ValidatorIn) GetOrgId() string {
	if x != nil {
		if x.xxx_hidden_OrgId != nil {
			return *x.xxx_hidden_OrgId
		}
		return ""
	}
	return ""
}

func (x *ValidatorIn) GetSkipToken() bool {
	if x != nil {
		return x.xxx_hidden_SkipToken
	}
	return false
}

func (x *ValidatorIn) SetPoint(v *common.DataPoint) {
	x.xxx_hidden_Point = v
}

func (x *ValidatorIn) SetOrgId(v string) {
	x.xxx_hidden_OrgId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ValidatorIn) SetSkipToken(v bool) {
	x.xxx_hidden_SkipToken = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ValidatorIn) HasPoint() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Point != nil
}

func (x *ValidatorIn) HasOrgId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ValidatorIn) HasSkipToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ValidatorIn) ClearPoint() {
	x.xxx_hidden_Point = nil
}

func (x *ValidatorIn) ClearOrgId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_OrgId = nil
}

func (x *ValidatorIn) ClearSkipToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SkipToken = false
}

type ValidatorIn_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Data point.
	Point *common.DataPoint
	// Organization ID (UUID). May be empty if generated internally (LoRaWAN, etc.).
	OrgId *string
	// Authentication has already taken place (API, LoRaWAN, etc.) and token validation can be skipped.
	SkipToken *bool
}

func (b0 ValidatorIn_builder) Build() *ValidatorIn {
	m0 := &ValidatorIn{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Point = b.Point
	if b.OrgId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_OrgId = b.OrgId
	}
	if b.SkipToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_SkipToken = *b.SkipToken
	}
	return m0
}

var File_message_thingspect_validator_in_proto protoreflect.FileDescriptor

const file_message_thingspect_validator_in_proto_rawDesc = "" +
	"\n" +
	"%message/thingspect_validator_in.proto\x12\x16thingspect.int.message\x1a!common/thingspect_datapoint.proto\"w\n" +
	"\vValidatorIn\x122\n" +
	"\x05point\x18\x01 \x01(\v2\x1c.thingspect.common.DataPointR\x05point\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"skip_token\x18\x03 \x01(\bR\tskipTokenB.Z,github.com/thingspect/atlas/proto/go/messageb\beditionsp\xe9\a"

var file_message_thingspect_validator_in_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_thingspect_validator_in_proto_goTypes = []any{
	(*ValidatorIn)(nil),      // 0: thingspect.int.message.ValidatorIn
	(*common.DataPoint)(nil), // 1: thingspect.common.DataPoint
}
var file_message_thingspect_validator_in_proto_depIdxs = []int32{
	1, // 0: thingspect.int.message.ValidatorIn.point:type_name -> thingspect.common.DataPoint
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_thingspect_validator_in_proto_init() }
func file_message_thingspect_validator_in_proto_init() {
	if File_message_thingspect_validator_in_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_thingspect_validator_in_proto_rawDesc), len(file_message_thingspect_validator_in_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_thingspect_validator_in_proto_goTypes,
		DependencyIndexes: file_message_thingspect_validator_in_proto_depIdxs,
		MessageInfos:      file_message_thingspect_validator_in_proto_msgTypes,
	}.Build()
	File_message_thingspect_validator_in_proto = out.File
	file_message_thingspect_validator_in_proto_goTypes = nil
	file_message_thingspect_validator_in_proto_depIdxs = nil
}
