// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: message/thingspect_decoder_in.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DecoderIn represents a data payload and associated metadata as used in message queues.
type DecoderIn struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UniqId      *string                `protobuf:"bytes,1,opt,name=uniq_id,json=uniqId"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,2,opt,name=data"`
	xxx_hidden_Ts          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts"`
	xxx_hidden_TraceId     []byte                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DecoderIn) Reset() {
	*x = DecoderIn{}
	mi := &file_message_thingspect_decoder_in_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecoderIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecoderIn) ProtoMessage() {}

func (x *DecoderIn) ProtoReflect() protoreflect.Message {
	mi := &file_message_thingspect_decoder_in_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DecoderIn) GetUniqId() string {
	if x != nil {
		if x.xxx_hidden_UniqId != nil {
			return *x.xxx_hidden_UniqId
		}
		return ""
	}
	return ""
}

func (x *DecoderIn) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *DecoderIn) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Ts
	}
	return nil
}

func (x *DecoderIn) GetTraceId() []byte {
	if x != nil {
		return x.xxx_hidden_TraceId
	}
	return nil
}

func (x *DecoderIn) SetUniqId(v string) {
	x.xxx_hidden_UniqId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *DecoderIn) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *DecoderIn) SetTs(v *timestamppb.Timestamp) {
	x.xxx_hidden_Ts = v
}

func (x *DecoderIn) SetTraceId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_TraceId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *DecoderIn) HasUniqId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DecoderIn) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DecoderIn) HasTs() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ts != nil
}

func (x *DecoderIn) HasTraceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *DecoderIn) ClearUniqId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_UniqId = nil
}

func (x *DecoderIn) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Data = nil
}

func (x *DecoderIn) ClearTs() {
	x.xxx_hidden_Ts = nil
}

func (x *DecoderIn) ClearTraceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_TraceId = nil
}

type DecoderIn_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Device unique ID.
	UniqId *string
	// Data payload.
	Data []byte
	// Timestamp.
	Ts *timestamppb.Timestamp
	// Trace ID (UUID).
	TraceId []byte
}

func (b0 DecoderIn_builder) Build() *DecoderIn {
	m0 := &DecoderIn{}
	b, x := &b0, m0
	_, _ = b, x
	if b.UniqId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_UniqId = b.UniqId
	}
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Data = b.Data
	}
	x.xxx_hidden_Ts = b.Ts
	if b.TraceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_TraceId = b.TraceId
	}
	return m0
}

var File_message_thingspect_decoder_in_proto protoreflect.FileDescriptor

const file_message_thingspect_decoder_in_proto_rawDesc = "" +
	"\n" +
	"#message/thingspect_decoder_in.proto\x12\x16thingspect.int.message\x1a\x1fgoogle/protobuf/timestamp.proto\"\x7f\n" +
	"\tDecoderIn\x12\x17\n" +
	"\auniq_id\x18\x01 \x01(\tR\x06uniqId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12*\n" +
	"\x02ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\fR\atraceIdB.Z,github.com/thingspect/atlas/proto/go/messageb\beditionsp\xe9\a"

var file_message_thingspect_decoder_in_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_thingspect_decoder_in_proto_goTypes = []any{
	(*DecoderIn)(nil),             // 0: thingspect.int.message.DecoderIn
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_message_thingspect_decoder_in_proto_depIdxs = []int32{
	1, // 0: thingspect.int.message.DecoderIn.ts:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_thingspect_decoder_in_proto_init() }
func file_message_thingspect_decoder_in_proto_init() {
	if File_message_thingspect_decoder_in_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_thingspect_decoder_in_proto_rawDesc), len(file_message_thingspect_decoder_in_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_thingspect_decoder_in_proto_goTypes,
		DependencyIndexes: file_message_thingspect_decoder_in_proto_depIdxs,
		MessageInfos:      file_message_thingspect_decoder_in_proto_msgTypes,
	}.Build()
	File_message_thingspect_decoder_in_proto = out.File
	file_message_thingspect_decoder_in_proto_goTypes = nil
	file_message_thingspect_decoder_in_proto_depIdxs = nil
}
