// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: message/thingspect_eventer_out.proto

package message

import (
	api "github.com/thingspect/proto/go/api"
	common "github.com/thingspect/proto/go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventerOut represents a data point and associated metadata as used in message queues.
type EventerOut struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Point  *common.DataPoint      `protobuf:"bytes,1,opt,name=point"`
	xxx_hidden_Device *api.Device            `protobuf:"bytes,2,opt,name=device"`
	xxx_hidden_Rule   *api.Rule              `protobuf:"bytes,3,opt,name=rule"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EventerOut) Reset() {
	*x = EventerOut{}
	mi := &file_message_thingspect_eventer_out_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventerOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventerOut) ProtoMessage() {}

func (x *EventerOut) ProtoReflect() protoreflect.Message {
	mi := &file_message_thingspect_eventer_out_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventerOut) GetPoint() *common.DataPoint {
	if x != nil {
		return x.xxx_hidden_Point
	}
	return nil
}

func (x *EventerOut) GetDevice() *api.Device {
	if x != nil {
		return x.xxx_hidden_Device
	}
	return nil
}

func (x *EventerOut) GetRule() *api.Rule {
	if x != nil {
		return x.xxx_hidden_Rule
	}
	return nil
}

func (x *EventerOut) SetPoint(v *common.DataPoint) {
	x.xxx_hidden_Point = v
}

func (x *EventerOut) SetDevice(v *api.Device) {
	x.xxx_hidden_Device = v
}

func (x *EventerOut) SetRule(v *api.Rule) {
	x.xxx_hidden_Rule = v
}

func (x *EventerOut) HasPoint() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Point != nil
}

func (x *EventerOut) HasDevice() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Device != nil
}

func (x *EventerOut) HasRule() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Rule != nil
}

func (x *EventerOut) ClearPoint() {
	x.xxx_hidden_Point = nil
}

func (x *EventerOut) ClearDevice() {
	x.xxx_hidden_Device = nil
}

func (x *EventerOut) ClearRule() {
	x.xxx_hidden_Rule = nil
}

type EventerOut_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Data point.
	Point *common.DataPoint
	// Device.
	Device *api.Device
	// Rule.
	Rule *api.Rule
}

func (b0 EventerOut_builder) Build() *EventerOut {
	m0 := &EventerOut{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Point = b.Point
	x.xxx_hidden_Device = b.Device
	x.xxx_hidden_Rule = b.Rule
	return m0
}

var File_message_thingspect_eventer_out_proto protoreflect.FileDescriptor

const file_message_thingspect_eventer_out_proto_rawDesc = "" +
	"\n" +
	"$message/thingspect_eventer_out.proto\x12\x16thingspect.int.message\x1a\x1bapi/thingspect_device.proto\x1a\x1fapi/thingspect_rule_alarm.proto\x1a!common/thingspect_datapoint.proto\"\x9a\x01\n" +
	"\n" +
	"EventerOut\x122\n" +
	"\x05point\x18\x01 \x01(\v2\x1c.thingspect.common.DataPointR\x05point\x12.\n" +
	"\x06device\x18\x02 \x01(\v2\x16.thingspect.api.DeviceR\x06device\x12(\n" +
	"\x04rule\x18\x03 \x01(\v2\x14.thingspect.api.RuleR\x04ruleB.Z,github.com/thingspect/atlas/proto/go/messageb\beditionsp\xe9\a"

var file_message_thingspect_eventer_out_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_thingspect_eventer_out_proto_goTypes = []any{
	(*EventerOut)(nil),       // 0: thingspect.int.message.EventerOut
	(*common.DataPoint)(nil), // 1: thingspect.common.DataPoint
	(*api.Device)(nil),       // 2: thingspect.api.Device
	(*api.Rule)(nil),         // 3: thingspect.api.Rule
}
var file_message_thingspect_eventer_out_proto_depIdxs = []int32{
	1, // 0: thingspect.int.message.EventerOut.point:type_name -> thingspect.common.DataPoint
	2, // 1: thingspect.int.message.EventerOut.device:type_name -> thingspect.api.Device
	3, // 2: thingspect.int.message.EventerOut.rule:type_name -> thingspect.api.Rule
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_message_thingspect_eventer_out_proto_init() }
func file_message_thingspect_eventer_out_proto_init() {
	if File_message_thingspect_eventer_out_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_thingspect_eventer_out_proto_rawDesc), len(file_message_thingspect_eventer_out_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_thingspect_eventer_out_proto_goTypes,
		DependencyIndexes: file_message_thingspect_eventer_out_proto_depIdxs,
		MessageInfos:      file_message_thingspect_eventer_out_proto_msgTypes,
	}.Build()
	File_message_thingspect_eventer_out_proto = out.File
	file_message_thingspect_eventer_out_proto_goTypes = nil
	file_message_thingspect_eventer_out_proto_depIdxs = nil
}
