// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: message/thingspect_decoder_in.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DecoderIn represents a data payload and associated metadata as used in message queues.
type DecoderIn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device unique ID.
	UniqId string `protobuf:"bytes,1,opt,name=uniq_id,json=uniqId,proto3" json:"uniq_id,omitempty"`
	// Data payload.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Timestamp.
	Ts *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	// Trace ID (UUID).
	TraceId       []byte `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecoderIn) Reset() {
	*x = DecoderIn{}
	mi := &file_message_thingspect_decoder_in_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecoderIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecoderIn) ProtoMessage() {}

func (x *DecoderIn) ProtoReflect() protoreflect.Message {
	mi := &file_message_thingspect_decoder_in_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecoderIn.ProtoReflect.Descriptor instead.
func (*DecoderIn) Descriptor() ([]byte, []int) {
	return file_message_thingspect_decoder_in_proto_rawDescGZIP(), []int{0}
}

func (x *DecoderIn) GetUniqId() string {
	if x != nil {
		return x.UniqId
	}
	return ""
}

func (x *DecoderIn) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DecoderIn) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *DecoderIn) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

var File_message_thingspect_decoder_in_proto protoreflect.FileDescriptor

const file_message_thingspect_decoder_in_proto_rawDesc = "" +
	"\n" +
	"#message/thingspect_decoder_in.proto\x12\x16thingspect.int.message\x1a\x1fgoogle/protobuf/timestamp.proto\"\x7f\n" +
	"\tDecoderIn\x12\x17\n" +
	"\auniq_id\x18\x01 \x01(\tR\x06uniqId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12*\n" +
	"\x02ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\fR\atraceIdB.Z,github.com/thingspect/atlas/proto/go/messageb\x06proto3"

var (
	file_message_thingspect_decoder_in_proto_rawDescOnce sync.Once
	file_message_thingspect_decoder_in_proto_rawDescData []byte
)

func file_message_thingspect_decoder_in_proto_rawDescGZIP() []byte {
	file_message_thingspect_decoder_in_proto_rawDescOnce.Do(func() {
		file_message_thingspect_decoder_in_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_thingspect_decoder_in_proto_rawDesc), len(file_message_thingspect_decoder_in_proto_rawDesc)))
	})
	return file_message_thingspect_decoder_in_proto_rawDescData
}

var file_message_thingspect_decoder_in_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_thingspect_decoder_in_proto_goTypes = []any{
	(*DecoderIn)(nil),             // 0: thingspect.int.message.DecoderIn
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_message_thingspect_decoder_in_proto_depIdxs = []int32{
	1, // 0: thingspect.int.message.DecoderIn.ts:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_thingspect_decoder_in_proto_init() }
func file_message_thingspect_decoder_in_proto_init() {
	if File_message_thingspect_decoder_in_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_thingspect_decoder_in_proto_rawDesc), len(file_message_thingspect_decoder_in_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_thingspect_decoder_in_proto_goTypes,
		DependencyIndexes: file_message_thingspect_decoder_in_proto_depIdxs,
		MessageInfos:      file_message_thingspect_decoder_in_proto_msgTypes,
	}.Build()
	File_message_thingspect_decoder_in_proto = out.File
	file_message_thingspect_decoder_in_proto_goTypes = nil
	file_message_thingspect_decoder_in_proto_depIdxs = nil
}
