DROP TYPE IF EXISTS alert_status;
CREATE TYPE alert_status AS ENUM ('ALERT_STATUS_UNSPECIFIED', 'SENT', 'ERROR');

ALTER TABLE alerts ADD COLUMN status alert_status NOT NULL DEFAULT 'ALERT_STATUS_UNSPECIFIED';
ALTER TABLE alerts ALTER COLUMN status DROP DEFAULT;
ALTER TABLE alerts ADD COLUMN error varchar(255) NOT NULL DEFAULT '';
ALTER TABLE alerts ALTER COLUMN error DROP DEFAULT;

DROP TYPE IF EXISTS alarm_type;
CREATE TYPE alarm_type AS ENUM ('ALARM_TYPE_UNSPECIFIED', 'APP');

ALTER TABLE alarms ADD COLUMN type alarm_type NOT NULL DEFAULT 'ALARM_TYPE_UNSPECIFIED';
ALTER TABLE alarms ALTER COLUMN type DROP DEFAULT;

ALTER TABLE users ADD COLUMN app_key varchar(80) NOT NULL DEFAULT '';
ALTER TABLE users ALTER COLUMN app_key DROP DEFAULT;
