DROP EXTENSION IF EXISTS pgcrypto;
ALTER TABLE orgs ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE devices ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE devices ALTER COLUMN token SET DEFAULT uuidv7();
ALTER TABLE users ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE rules ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE alarms ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE keys ALTER COLUMN id SET DEFAULT uuidv7();
