// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: token/thingspect_web.proto

package token

import (
	api "github.com/thingspect/proto/go/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Web represents a web or API key token.
type Web struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_IdOneof     isWeb_IdOneof          `protobuf_oneof:"id_oneof"`
	xxx_hidden_OrgId       []byte                 `protobuf:"bytes,3,opt,name=org_id,json=orgId"`
	xxx_hidden_Role        api.Role               `protobuf:"varint,4,opt,name=role,enum=thingspect.api.Role"`
	xxx_hidden_ExpiresAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Web) Reset() {
	*x = Web{}
	mi := &file_token_thingspect_web_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Web) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Web) ProtoMessage() {}

func (x *Web) ProtoReflect() protoreflect.Message {
	mi := &file_token_thingspect_web_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Web) GetUserId() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_IdOneof.(*web_UserId); ok {
			return x.UserId
		}
	}
	return nil
}

func (x *Web) GetKeyId() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_IdOneof.(*web_KeyId); ok {
			return x.KeyId
		}
	}
	return nil
}

func (x *Web) GetOrgId() []byte {
	if x != nil {
		return x.xxx_hidden_OrgId
	}
	return nil
}

func (x *Web) GetRole() api.Role {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Role
		}
	}
	return api.Role(0)
}

func (x *Web) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiresAt
	}
	return nil
}

func (x *Web) SetUserId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_IdOneof = &web_UserId{v}
}

func (x *Web) SetKeyId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_IdOneof = &web_KeyId{v}
}

func (x *Web) SetOrgId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_OrgId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *Web) SetRole(v api.Role) {
	x.xxx_hidden_Role = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *Web) SetExpiresAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiresAt = v
}

func (x *Web) HasIdOneof() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_IdOneof != nil
}

func (x *Web) HasUserId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_IdOneof.(*web_UserId)
	return ok
}

func (x *Web) HasKeyId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_IdOneof.(*web_KeyId)
	return ok
}

func (x *Web) HasOrgId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Web) HasRole() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Web) HasExpiresAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiresAt != nil
}

func (x *Web) ClearIdOneof() {
	x.xxx_hidden_IdOneof = nil
}

func (x *Web) ClearUserId() {
	if _, ok := x.xxx_hidden_IdOneof.(*web_UserId); ok {
		x.xxx_hidden_IdOneof = nil
	}
}

func (x *Web) ClearKeyId() {
	if _, ok := x.xxx_hidden_IdOneof.(*web_KeyId); ok {
		x.xxx_hidden_IdOneof = nil
	}
}

func (x *Web) ClearOrgId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_OrgId = nil
}

func (x *Web) ClearRole() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Role = api.Role_ROLE_UNSPECIFIED
}

func (x *Web) ClearExpiresAt() {
	x.xxx_hidden_ExpiresAt = nil
}

const Web_IdOneof_not_set_case case_Web_IdOneof = 0
const Web_UserId_case case_Web_IdOneof = 1
const Web_KeyId_case case_Web_IdOneof = 2

func (x *Web) WhichIdOneof() case_Web_IdOneof {
	if x == nil {
		return Web_IdOneof_not_set_case
	}
	switch x.xxx_hidden_IdOneof.(type) {
	case *web_UserId:
		return Web_UserId_case
	case *web_KeyId:
		return Web_KeyId_case
	default:
		return Web_IdOneof_not_set_case
	}
}

type Web_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// User identifier.

	// Fields of oneof xxx_hidden_IdOneof:
	// User ID (UUID). Either user ID or key ID must be provided.
	UserId []byte
	// Key ID (UUID). Either user ID or key ID must be provided.
	KeyId []byte
	// -- end of xxx_hidden_IdOneof
	// Organization ID (UUID).
	OrgId []byte
	// User role.
	Role *api.Role
	// Token expiration timestamp. If present, nanos should be zeroed for compactness. Will not be present for API key use.
	ExpiresAt *timestamppb.Timestamp
}

func (b0 Web_builder) Build() *Web {
	m0 := &Web{}
	b, x := &b0, m0
	_, _ = b, x
	if b.UserId != nil {
		x.xxx_hidden_IdOneof = &web_UserId{b.UserId}
	}
	if b.KeyId != nil {
		x.xxx_hidden_IdOneof = &web_KeyId{b.KeyId}
	}
	if b.OrgId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_OrgId = b.OrgId
	}
	if b.Role != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Role = *b.Role
	}
	x.xxx_hidden_ExpiresAt = b.ExpiresAt
	return m0
}

type case_Web_IdOneof protoreflect.FieldNumber

func (x case_Web_IdOneof) String() string {
	md := file_token_thingspect_web_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isWeb_IdOneof interface {
	isWeb_IdOneof()
}

type web_UserId struct {
	// User ID (UUID). Either user ID or key ID must be provided.
	UserId []byte `protobuf:"bytes,1,opt,name=user_id,json=userId,oneof"`
}

type web_KeyId struct {
	// Key ID (UUID). Either user ID or key ID must be provided.
	KeyId []byte `protobuf:"bytes,2,opt,name=key_id,json=keyId,oneof"`
}

func (*web_UserId) isWeb_IdOneof() {}

func (*web_KeyId) isWeb_IdOneof() {}

var File_token_thingspect_web_proto protoreflect.FileDescriptor

const file_token_thingspect_web_proto_rawDesc = "" +
	"\n" +
	"\x1atoken/thingspect_web.proto\x12\x14thingspect.int.token\x1a\x19api/thingspect_role.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x01\n" +
	"\x03Web\x12\x19\n" +
	"\auser_id\x18\x01 \x01(\fH\x00R\x06userId\x12\x17\n" +
	"\x06key_id\x18\x02 \x01(\fH\x00R\x05keyId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\fR\x05orgId\x12(\n" +
	"\x04role\x18\x04 \x01(\x0e2\x14.thingspect.api.RoleR\x04role\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAtB\n" +
	"\n" +
	"\bid_oneofB,Z*github.com/thingspect/atlas/proto/go/tokenb\beditionsp\xe9\a"

var file_token_thingspect_web_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_token_thingspect_web_proto_goTypes = []any{
	(*Web)(nil),                   // 0: thingspect.int.token.Web
	(api.Role)(0),                 // 1: thingspect.api.Role
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_token_thingspect_web_proto_depIdxs = []int32{
	1, // 0: thingspect.int.token.Web.role:type_name -> thingspect.api.Role
	2, // 1: thingspect.int.token.Web.expires_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_token_thingspect_web_proto_init() }
func file_token_thingspect_web_proto_init() {
	if File_token_thingspect_web_proto != nil {
		return
	}
	file_token_thingspect_web_proto_msgTypes[0].OneofWrappers = []any{
		(*web_UserId)(nil),
		(*web_KeyId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_token_thingspect_web_proto_rawDesc), len(file_token_thingspect_web_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_token_thingspect_web_proto_goTypes,
		DependencyIndexes: file_token_thingspect_web_proto_depIdxs,
		MessageInfos:      file_token_thingspect_web_proto_msgTypes,
	}.Build()
	File_token_thingspect_web_proto = out.File
	file_token_thingspect_web_proto_goTypes = nil
	file_token_thingspect_web_proto_depIdxs = nil
}
