// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.4
// source: token/thingspect_web.proto

package token

import (
	api "github.com/thingspect/proto/go/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Web represents a web or API key token.
type Web struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User identifier.
	//
	// Types that are valid to be assigned to IdOneof:
	//
	//	*Web_UserId
	//	*Web_KeyId
	IdOneof isWeb_IdOneof `protobuf_oneof:"id_oneof"`
	// Organization ID (UUID).
	OrgId []byte `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// User role.
	Role api.Role `protobuf:"varint,4,opt,name=role,proto3,enum=thingspect.api.Role" json:"role,omitempty"`
	// Token expiration timestamp. If present, nanos should be zeroed for compactness. Will not be present for API key use.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Web) Reset() {
	*x = Web{}
	mi := &file_token_thingspect_web_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Web) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Web) ProtoMessage() {}

func (x *Web) ProtoReflect() protoreflect.Message {
	mi := &file_token_thingspect_web_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Web.ProtoReflect.Descriptor instead.
func (*Web) Descriptor() ([]byte, []int) {
	return file_token_thingspect_web_proto_rawDescGZIP(), []int{0}
}

func (x *Web) GetIdOneof() isWeb_IdOneof {
	if x != nil {
		return x.IdOneof
	}
	return nil
}

func (x *Web) GetUserId() []byte {
	if x != nil {
		if x, ok := x.IdOneof.(*Web_UserId); ok {
			return x.UserId
		}
	}
	return nil
}

func (x *Web) GetKeyId() []byte {
	if x != nil {
		if x, ok := x.IdOneof.(*Web_KeyId); ok {
			return x.KeyId
		}
	}
	return nil
}

func (x *Web) GetOrgId() []byte {
	if x != nil {
		return x.OrgId
	}
	return nil
}

func (x *Web) GetRole() api.Role {
	if x != nil {
		return x.Role
	}
	return api.Role(0)
}

func (x *Web) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type isWeb_IdOneof interface {
	isWeb_IdOneof()
}

type Web_UserId struct {
	// User ID (UUID). Either user ID or key ID must be provided.
	UserId []byte `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3,oneof"`
}

type Web_KeyId struct {
	// Key ID (UUID). Either user ID or key ID must be provided.
	KeyId []byte `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3,oneof"`
}

func (*Web_UserId) isWeb_IdOneof() {}

func (*Web_KeyId) isWeb_IdOneof() {}

var File_token_thingspect_web_proto protoreflect.FileDescriptor

const file_token_thingspect_web_proto_rawDesc = "" +
	"\n" +
	"\x1atoken/thingspect_web.proto\x12\x14thingspect.int.token\x1a\x19api/thingspect_role.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x01\n" +
	"\x03Web\x12\x19\n" +
	"\auser_id\x18\x01 \x01(\fH\x00R\x06userId\x12\x17\n" +
	"\x06key_id\x18\x02 \x01(\fH\x00R\x05keyId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\fR\x05orgId\x12(\n" +
	"\x04role\x18\x04 \x01(\x0e2\x14.thingspect.api.RoleR\x04role\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAtB\n" +
	"\n" +
	"\bid_oneofB,Z*github.com/thingspect/atlas/proto/go/tokenb\x06proto3"

var (
	file_token_thingspect_web_proto_rawDescOnce sync.Once
	file_token_thingspect_web_proto_rawDescData []byte
)

func file_token_thingspect_web_proto_rawDescGZIP() []byte {
	file_token_thingspect_web_proto_rawDescOnce.Do(func() {
		file_token_thingspect_web_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_token_thingspect_web_proto_rawDesc), len(file_token_thingspect_web_proto_rawDesc)))
	})
	return file_token_thingspect_web_proto_rawDescData
}

var file_token_thingspect_web_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_token_thingspect_web_proto_goTypes = []any{
	(*Web)(nil),                   // 0: thingspect.int.token.Web
	(api.Role)(0),                 // 1: thingspect.api.Role
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_token_thingspect_web_proto_depIdxs = []int32{
	1, // 0: thingspect.int.token.Web.role:type_name -> thingspect.api.Role
	2, // 1: thingspect.int.token.Web.expires_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_token_thingspect_web_proto_init() }
func file_token_thingspect_web_proto_init() {
	if File_token_thingspect_web_proto != nil {
		return
	}
	file_token_thingspect_web_proto_msgTypes[0].OneofWrappers = []any{
		(*Web_UserId)(nil),
		(*Web_KeyId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_token_thingspect_web_proto_rawDesc), len(file_token_thingspect_web_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_token_thingspect_web_proto_goTypes,
		DependencyIndexes: file_token_thingspect_web_proto_depIdxs,
		MessageInfos:      file_token_thingspect_web_proto_msgTypes,
	}.Build()
	File_token_thingspect_web_proto = out.File
	file_token_thingspect_web_proto_goTypes = nil
	file_token_thingspect_web_proto_depIdxs = nil
}
