// Code generated by MockGen. DO NOT EDIT.
// Source: cacher.go
//
// Generated by this command:
//
//	mockgen -source cacher.go -destination mock_cacher.go -package cache
//

// Package cache is a generated GoMock package.
package cache

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCacher is a mock of Cacher interface.
type MockCacher[V any] struct {
	ctrl     *gomock.Controller
	recorder *MockCacherMockRecorder[V]
	isgomock struct{}
}

// MockCacherMockRecorder is the mock recorder for MockCacher.
type MockCacherMockRecorder[V any] struct {
	mock *MockCacher[V]
}

// NewMockCacher creates a new mock instance.
func NewMockCacher[V any](ctrl *gomock.Controller) *MockCacher[V] {
	mock := &MockCacher[V]{ctrl: ctrl}
	mock.recorder = &MockCacherMockRecorder[V]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacher[V]) EXPECT() *MockCacherMockRecorder[V] {
	return m.recorder
}

// Close mocks base method.
func (m *MockCacher[V]) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCacherMockRecorder[V]) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCacher[V])(nil).Close))
}

// Del mocks base method.
func (m *MockCacher[V]) Del(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Del", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockCacherMockRecorder[V]) Del(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockCacher[V])(nil).Del), ctx, key)
}

// Get mocks base method.
func (m *MockCacher[V]) Get(ctx context.Context, key string) (V, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(V)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCacherMockRecorder[V]) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCacher[V])(nil).Get), ctx, key)
}

// Incr mocks base method.
func (m *MockCacher[V]) Incr(ctx context.Context, key string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Incr", ctx, key)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Incr indicates an expected call of Incr.
func (mr *MockCacherMockRecorder[V]) Incr(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Incr", reflect.TypeOf((*MockCacher[V])(nil).Incr), ctx, key)
}

// Set mocks base method.
func (m *MockCacher[V]) Set(ctx context.Context, key string, value V) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacherMockRecorder[V]) Set(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCacher[V])(nil).Set), ctx, key, value)
}

// SetIfNotExist mocks base method.
func (m *MockCacher[V]) SetIfNotExist(ctx context.Context, key string, value V) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIfNotExist", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetIfNotExist indicates an expected call of SetIfNotExist.
func (mr *MockCacherMockRecorder[V]) SetIfNotExist(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIfNotExist", reflect.TypeOf((*MockCacher[V])(nil).SetIfNotExist), ctx, key, value)
}

// SetIfNotExistTTL mocks base method.
func (m *MockCacher[V]) SetIfNotExistTTL(ctx context.Context, key string, value V, exp time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIfNotExistTTL", ctx, key, value, exp)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetIfNotExistTTL indicates an expected call of SetIfNotExistTTL.
func (mr *MockCacherMockRecorder[V]) SetIfNotExistTTL(ctx, key, value, exp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIfNotExistTTL", reflect.TypeOf((*MockCacher[V])(nil).SetIfNotExistTTL), ctx, key, value, exp)
}

// SetTTL mocks base method.
func (m *MockCacher[V]) SetTTL(ctx context.Context, key string, value V, exp time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTTL", ctx, key, value, exp)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTTL indicates an expected call of SetTTL.
func (mr *MockCacherMockRecorder[V]) SetTTL(ctx, key, value, exp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTTL", reflect.TypeOf((*MockCacher[V])(nil).SetTTL), ctx, key, value, exp)
}
