// Code generated by MockGen. DO NOT EDIT.
// Source: rule.go
//
// Generated by this command:
//
//	mockgen -source rule.go -destination mock_ruler_test.go -package service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"
	time "time"

	api "github.com/thingspect/proto/go/api"
	gomock "go.uber.org/mock/gomock"
)

// MockRuler is a mock of Ruler interface.
type MockRuler struct {
	ctrl     *gomock.Controller
	recorder *MockRulerMockRecorder
}

// MockRulerMockRecorder is the mock recorder for MockRuler.
type MockRulerMockRecorder struct {
	mock *MockRuler
}

// NewMockRuler creates a new mock instance.
func NewMockRuler(ctrl *gomock.Controller) *MockRuler {
	mock := &MockRuler{ctrl: ctrl}
	mock.recorder = &MockRulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuler) EXPECT() *MockRulerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRuler) Create(ctx context.Context, rule *api.Rule) (*api.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rule)
	ret0, _ := ret[0].(*api.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRulerMockRecorder) Create(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRuler)(nil).Create), ctx, rule)
}

// Delete mocks base method.
func (m *MockRuler) Delete(ctx context.Context, ruleID, orgID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, ruleID, orgID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRulerMockRecorder) Delete(ctx, ruleID, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRuler)(nil).Delete), ctx, ruleID, orgID)
}

// List mocks base method.
func (m *MockRuler) List(ctx context.Context, orgID string, lBoundTS time.Time, prevID string, limit int32) ([]*api.Rule, int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, orgID, lBoundTS, prevID, limit)
	ret0, _ := ret[0].([]*api.Rule)
	ret1, _ := ret[1].(int32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockRulerMockRecorder) List(ctx, orgID, lBoundTS, prevID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRuler)(nil).List), ctx, orgID, lBoundTS, prevID, limit)
}

// Read mocks base method.
func (m *MockRuler) Read(ctx context.Context, ruleID, orgID string) (*api.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx, ruleID, orgID)
	ret0, _ := ret[0].(*api.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockRulerMockRecorder) Read(ctx, ruleID, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockRuler)(nil).Read), ctx, ruleID, orgID)
}

// Update mocks base method.
func (m *MockRuler) Update(ctx context.Context, rule *api.Rule) (*api.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, rule)
	ret0, _ := ret[0].(*api.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRulerMockRecorder) Update(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRuler)(nil).Update), ctx, rule)
}
