name: Atlas CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: golang:1.16-alpine
      env:
        DOCKER: "y"
        # RACE: "y"
        TEST_PG_URI: postgres://postgres:postgres@postgres/atlas_test
        TEST_NSQ_PUB_ADDR: nsqd:4150
        TEST_NSQ_LOOKUP_ADDRS: nsqlookupd:4161
        TEST_MQTT_ADDR: tcp://mqtt:1883
    env:
      SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: atlas_test
      nsqlookupd:
        image: thingspect/nsqlookupd:v1.2.0
        env:
          LOG_LEVEL: warn
      nsqd:
        image: thingspect/nsqd:v1.2.0
        env:
          LOOKUP_ADDR: nsqlookupd:4160
          LOG_LEVEL: warn
      mqtt:
        image: eclipse-mosquitto:2.0
        volumes:
          - ${{ github.workspace }}/build/volume/mosquitto:/mosquitto/config
        options: --name mqtt
    steps:
      - name: Deps
        # Names are duplicated as IDs for important steps for use by Notify
        id: Deps
        # Add packages needed to support builds, tests, and optionally -race
        run: |
          apk update && apk upgrade
          apk add --no-cache make git #gcc musl-dev
          go version
          go env
      - name: Clone
        id: Clone
        uses: actions/checkout@v2
      - name: Restart_MQTT
        id: Restart_MQTT
        # Restart MQTT after volumes have been checked out
        uses: docker://docker
        with:
          args: docker restart mqtt
      - name: Build_and_Test
        id: Build_and_Test
        run: make test
      - name: Push
        id: Push
        # GitHub Actions do not currently support builds within a container
        run: |
          apk add --no-cache docker
          docker version
          docker login -u thingspect -p ${{ secrets.GHCR_PAT }} ghcr.io
          TAG=$(git rev-parse --short=8 HEAD)
          docker build -f build/Dockerfile -t ghcr.io/thingspect/atlas:${TAG} .
          docker push ghcr.io/thingspect/atlas:${TAG}
          docker logout ghcr.io
      - name: Notify
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
