name: Atlas CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: golang:1.19-alpine
      env:
        GOFLAGS: -buildvcs=false
        TEST_REDIS_HOST: redis
        TEST_PG_URI: pgx://postgres:postgres@postgres/atlas_test
        TEST_NSQ_PUB_ADDR: nsqd:4150
        TEST_NSQ_LOOKUP_ADDRS: nsqlookupd:4161
        TEST_MQTT_ADDR: tcp://mqtt:1883
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: atlas_test
      nsqlookupd:
        image: thingspect/nsqlookupd:v1.2.1
        env:
          LOG_LEVEL: warn
      nsqd:
        image: thingspect/nsqd:v1.2.1
        env:
          LOOKUP_ADDR: nsqlookupd:4160
          LOG_LEVEL: warn
      mqtt:
        image: eclipse-mosquitto:2.0
        volumes:
          - ${{ github.workspace }}/build/volume/mosquitto:/mosquitto/config
        options: --name mqtt
      redis:
        image: redis:7-alpine
    steps:
      - name: Deps
        # Names are duplicated as IDs for use by Notify
        id: Deps
        # Add packages needed to support builds and tests
        run: |
          apk update && apk upgrade
          apk add --no-cache make git
          go version
          go env
      - name: Clone
        id: Clone
        uses: actions/checkout@v2
      - name: Restart_MQTT
        id: Restart_MQTT
        # Restart MQTT after volumes have been checked out
        uses: docker://docker
        with:
          args: docker restart mqtt
      - name: Build_and_Test
        id: Build_and_Test
        run: make test
      - name: Push
        id: Push
        # GitHub Actions does not currently support Docker within a container
        run: |
          apk add --no-cache docker
          docker version
          docker login -u thingspect -p ${{ secrets.GHCR_PAT }} ghcr.io
          git config --global --add safe.directory /__w/atlas/atlas
          TAG=$(git rev-parse --short=8 HEAD)
          #docker buildx create --use
          #docker buildx build -f build/Dockerfile -t ghcr.io/thingspect/atlas:${TAG} --platform linux/amd64,linux/arm64 --push .
          docker build -f build/Dockerfile -t ghcr.io/thingspect/atlas:${TAG} .
          docker push ghcr.io/thingspect/atlas:${TAG}
          #docker buildx rm
          docker logout ghcr.io
      - name: Notify
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
